from __future__ import annotations

CATEGORIES = {
    "sports": [
        "win",
        "beat",
        "game",
        "match",
        "nba",
        "nfl",
        "mlb",
        "ufc",
        "boxing",
        "nhl",
        "playoffs",
        "championship",
        "finals",
        "mvp",
        "tennis",
        "soccer",
        "superbowl",
        "world series",
        "score",
        "points",
        "goal",
        "touchdown",
    ],
    "crypto": [
        "bitcoin",
        "btc",
        "eth",
        "ethereum",
        "crypto",
        "solana",
        "xrp",
        "token",
        "blockchain",
        "defi",
        "nft",
        "binance",
        "coinbase",
        "doge",
        "memecoin",
        "altcoin",
        "usdt",
        "usdc",
        "stablecoin",
        "web3",
    ],
    "politics": [
        "trump",
        "biden",
        "election",
        "vote",
        "president",
        "congress",
        "senate",
        "democrat",
        "republican",
        "gop",
        "nominee",
        "primary",
        "cabinet",
        "poll",
        "governor",
        "mayor",
        "impeach",
        "ballot",
    ],
    "world": [
        "war",
        "russia",
        "ukraine",
        "china",
        "israel",
        "nato",
        "military",
        "gaza",
        "iran",
        "north korea",
        "taiwan",
        "ceasefire",
        "sanctions",
        "invasion",
        "conflict",
        "peace",
        "treaty",
    ],
    "tech": [
        "ai",
        "openai",
        "gpt",
        "apple",
        "google",
        "meta",
        "microsoft",
        "tesla",
        "nvidia",
        "spacex",
        "chatgpt",
        "anthropic",
        "iphone",
        "android",
        "launch",
        "release",
        "update",
        "model",
        "chip",
    ],
    "finance": [
        "stock",
        "market",
        "fed",
        "rate",
        "inflation",
        "gdp",
        "recession",
        "dow",
        "nasdaq",
        "treasury",
        "bond",
        "earnings",
        "interest",
        "ipo",
        "merger",
        "acquisition",
        "bank",
    ],
    "entertainment": [
        "oscar",
        "grammy",
        "emmy",
        "movie",
        "album",
        "award",
        "netflix",
        "disney",
        "spotify",
        "taylor swift",
        "box office",
        "streaming",
    ],
}

STRONG_POS = ["definitely", "certainly", "absolutely", "confirmed", "guaranteed", "will"]
WEAK_POS = ["likely", "probably", "expected", "should", "may", "could", "might"]
OUTCOME_POS = [
    "win",
    "pass",
    "above",
    "reach",
    "exceed",
    "approve",
    "achieve",
    "surge",
    "rise",
    "grow",
    "gain",
    "beat",
    "success",
    "record",
    "hit",
    "breakthrough",
    "victory",
    "triumph",
    "accomplish",
]
OUTCOME_NEG = [
    "lose",
    "fail",
    "below",
    "drop",
    "crash",
    "reject",
    "decline",
    "fall",
    "miss",
    "collapse",
    "plunge",
    "default",
    "bankrupt",
    "defeat",
    "loss",
    "unable",
    "never",
]

MONTH_NAMES = [
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
]

PLAYER_PROP_KEYWORDS = ["points", "rebounds", "assists", "yards", "touchdowns"]
TEAM_TOTAL_KEYWORDS = ["team total", "total points", "total goals"]
FINANCE_THRESHOLD_KEYWORDS = ["$", "market cap", "price of", "above", "below"]
HIGH_AMBIGUITY_KEYWORDS = ["at least", "roughly", "around", "approximately", "or more", "or less"]


def build_year_tokens(start_year: int = 2023, end_year: int = 2029) -> list[str]:
    return [str(year) for year in range(start_year, end_year)]
